### ISSUE TITLE
style参数里的width不生效

### ISSUE THREAD

**Issue by Hzy0913** [tinper-bee/bee-message#2]
v2.0.4版本里的设置宽度可能存在问题

![image](https://user-images.githubusercontent.com/22450881/58234157-80124180-7d70-11e9-9250-ac2c69bc78a7.png)

**Comment by Hzy0913** [comment]
查了下源码没有这个，可能是被内部覆盖了，关掉了先

**Comment by Hzy0913** [comment]
`config` 方法不支持style参数吗

**Comment by yangchch6** [comment]
> `config` 方法不支持style参数吗

![image](https://user-images.githubusercontent.com/33412781/58246170-f58a0c00-7d88-11e9-8fec-165623485ce7.png)
`config` 方法可以设置 width，对 `topRight / topLeft / bottomRight / bottomLeft` 位置的消息组件有效
